"""
Central rarity definitions for the bot.

Rarity is stored in the database as an integer key (1-6). Everything else
(display name, fallback emoji, premium custom emoji id) is looked up from
here at display time. This means:

  - Changing an emoji or a name later only requires editing this file,
    not touching every character document in the database.
  - `custom_emoji_id` is the numeric id Telegram assigns to a premium
    emoji you own. It cannot be generated by code - you get it from
    Telegram (e.g. by forwarding a message containing the premium emoji
    to a bot like @idstickerbot / @RawDataBot, or reading it off the
    message entities). Until you fill these in, `premium_id` stays None
    and the bot safely falls back to the plain emoji.

Usage:
    from shivu.rarity import RARITY_MAP, RARITY_WEIGHTS, format_rarity_html, get_rarity_name
"""

# rarity_key -> {name, emoji (fallback shown to non-premium / after a
# no-forward-tag forward), premium_id (Telegram custom emoji id)}
RARITY_MAP = {
    1: {"name": "Common",   "emoji": "🔵", "premium_id": "6219726962370289232"},
    2: {"name": "Rare",     "emoji": "🟠", "premium_id": "6224452757835752311"},
    3: {"name": "Legendary","emoji": "🟡", "premium_id": "6219595845608677184"},
    4: {"name": "Mythic",   "emoji": "💠", "premium_id": "6224516447905783899"},
    5: {"name": "Astral",  "emoji": "🌌", "premium_id": "6221737208928281346"},
    6: {"name": "Seraphic", "emoji": "🪽", "premium_id": "6224022079990146834"},
}

# Drop weights used by send_image()'s random.choices(). Higher = more common.
# Roughly halves at each step so rarity feels like it's actually getting rarer.
RARITY_WEIGHTS = {
    1: 100,  # 🔵 Common
    2: 50,   # 🟠 Rare
    3: 25,   # 🟡 Legendary
    4: 12,   # 💠 Mythic
    5: 5,    # 🌌 Astral
    6: 2,    # 🪽 Seraphic
}


def get_rarity_name(rarity_key: int) -> str:
    """Plain name only, e.g. 'Mythic'. Use where no emoji/HTML is wanted."""
    entry = RARITY_MAP.get(rarity_key)
    return entry["name"] if entry else "Unknown"


def get_rarity_emoji(rarity_key: int) -> str:
    """Plain fallback emoji only, e.g. '💠'."""
    entry = RARITY_MAP.get(rarity_key)
    return entry["emoji"] if entry else ""


def format_rarity_html(rarity_key: int) -> str:
    """
    HTML-ready rarity string for captions sent with parse_mode='HTML'.

    If a premium_id is set, wraps the fallback emoji in a <tg-emoji> tag so
    Telegram Premium accounts see the custom emoji. If premium_id is None
    (not filled in yet), just returns the plain emoji + name - completely
    safe to use before the premium emoji ids are added.

    Example output once premium_id is filled in:
        '<tg-emoji emoji-id="5368324170671202286">💠</tg-emoji> Mythic'
    Example output while premium_id is still None:
        '💠 Mythic'
    """
    entry = RARITY_MAP.get(rarity_key)
    if not entry:
        return "Unknown"

    name = entry["name"]
    emoji = entry["emoji"]
    premium_id = entry["premium_id"]

    if premium_id:
        return f'<tg-emoji emoji-id="{premium_id}">{emoji}</tg-emoji> {name}'
    return f'{emoji} {name}'


def format_rarity_plain_html(rarity_key: int) -> str:
    """
    Same output as format_rarity_html but WITHOUT the <tg-emoji> wrapper -
    always plain emoji + name, regardless of whether premium_id is set.

    Why this exists: Telegram will not render a custom/premium emoji inside
    the *initial* content of an answerInlineQuery result no matter what -
    not even if the bot owner has Telegram Premium. The entity is only
    allowed in messages the bot sends/edits directly (sendMessage,
    sendPhoto, editMessageCaption, etc.) to a private/group/supergroup chat.

    So inlinequery.py uses this plain version for the caption it first
    answers the inline query with, then swaps in format_rarity_html()'s
    version via edit_message_caption once chosen_inline_result confirms the
    result was actually sent into a chat.
    """
    entry = RARITY_MAP.get(rarity_key)
    if not entry:
        return "Unknown"
    return f'{entry["emoji"]} {entry["name"]}'


def is_valid_rarity(rarity_key: int) -> bool:
    return rarity_key in RARITY_MAP
